Cpa 522 - Default landing Page Option
cisagov/con-pca-api pull request #88
Opened 2020-09-10 22:17 UTC by dylanj1752

## 🗣 Description

Added default landing page option to landing page dropdown on template selection. Will use the default landing page at time of campaign creation when this is selected. 

If no landing page is selected (left blank) it will automatically use the default landing page. A landing page is no longer a required field on the template editor

## 💭 Motivation and Context

## 🧪 Testing

## 📷 Screenshots (if appropriate)

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-09-10 23:58 UTC, zenine07 commented on src/api/utils/aws_utils.py
> +<<<<<<< HEAD
Is that supposed to be here?

2020-09-10 23:58 UTC, zenine07 commented on src/api/utils/aws_utils.py
> +>>>>>>> develop
Same with this. looks like some weird merge results

2020-09-10 23:59 UTC, zenine07 requested changes
Just the comments on the lines I mentioned. Looks like a bad merge or something.

2020-09-15 19:27 UTC, dylanj1752 commented
Oddities with merge request. All necessary changes will be included in next push, closing this one

2020-09-15 19:27 UTC, closed without merging